[data]
input = "/path/to/visium/input.h5ad"
output = "/path/for/banksy_output/visium"
sample_name = "sample_01"
spatial_key = "spatial"

[parameters]
lambdas = []
resolutions = []
pca_dims = [20]
num_neighbours = 30
num_nn = 50
max_m = 1
seed = 1234
add_umap = false
scatter_size = 0.5
