[data]
input = "/path/to/visiumHD_008um_BANKSY_input_2000HVG.h5ad"
output = "/path/to/banksy_output/visium"
sample_name = "sample_01"
spatial_key = "spatial"

[parameters]
lambdas = [0.2, 0.8]
resolutions = [0.1, 0.2, 0.3]
pca_dims = [20]
num_neighbours = 30
num_nn = 50
max_m = 1
seed = 1234
add_umap = false
scatter_size = 0.5
